= Project: {Side_1}

=== Author: azmm12 .
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 05/07/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Getting started with controlling and programming Low Level Motors to reach the level of brushless motor contolling
The project is a controlled servo motor by a potentiometer , the motor should rotate to the same position of potentiometer of joystic .

== Installation Steps:
1. Open TinkerCad Website .
2. Connect Arduino Uno and Servo Motor and Potentiometer .
3. Download Servo Motor Library .
4. Use Block Coding Method .
5. Simulate the Code.

=== Folder structure

....
 Side_Mission_1        => Arduino sketch folder
  ├── Side_1.ino       => main Arduino file
  ├── Servo_Motor.png  => an image of the required schematics
  └── ReadMe.adoc      => Readme file
....

=== Contributing
To contribute to this project please contact azmm12 https://id.arduino.cc/azmm12

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
